import { Component } from '@angular/core';
import { TechConfig } from '../Util/types';

@Component({
  selector: 'app-tech',
  templateUrl: './tech.component.html',
  styleUrls: ['./tech.component.scss'],
})
export class TechComponent {
  techArray: TechConfig[] = [
    {
      url: '../../assets/icons/angular.png',
      alt: 'Angular Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Angular',
    },
    {
      url: '../../assets/icons/typescript.png',
      alt: 'TypeScript Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'TypeScript',
    },
    {
      url: '../../assets/icons/react.png',
      alt: 'React Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'React',
    },
    {
      url: '../../assets/icons/nextjs.png',
      alt: 'Nextjs Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'NextJs',
    },
    {
      url: '../../assets/icons/nodejs.png',
      alt: 'Node JS Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Node JS',
    },
    {
      url: '../../assets/icons/js.png',
      alt: 'JavaScript Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'JavaScript',
    },
    {
      url: '../../assets/icons/html-5.png',
      alt: 'HTML Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'HTML',
    },
    {
      url: '../../assets/icons/css-3.png',
      alt: 'CSS Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'CSS',
    },
    {
      url: '../../assets/icons/tailwind.png',
      alt: 'Tailwind Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Tailwind',
    },
    {
      url: '../../assets/icons/sass.png',
      alt: 'Sass Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Sass',
    },
    {
      url: '../../assets/icons/aws.png',
      alt: 'AWS Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'AWS',
    },
    {
      url: '../../assets/icons/azure.png',
      alt: 'Azure Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Azure',
    },
    {
      url: '../../assets/icons/express.png',
      alt: 'Express JS Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Express JS',
    },
    {
      url: '../../assets/icons/github.png',
      alt: 'Github Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Github',
    },
    {
      url: '../../assets/icons/mongoDb.png',
      alt: 'Mongo DB Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Mongo DB',
    },
    {
      url: '../../assets/icons/docker.png',
      alt: 'Dcoker Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Docker',
    },
    {
      url: '../../assets/icons/git.png',
      alt: 'Git Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Git',
    },
    {
      url: '../../assets/icons/postgreSQL.png',
      alt: 'Postgre SQL Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Postgre SQL',
    },
    {
      url: '../../assets/icons/gha.png',
      alt: 'Github Action Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Github Action',
    },
    {
      url: '../../assets/icons/sql.png',
      alt: 'SQL Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'SQL',
    },
    {
      url: '../../assets/icons/jwt.png',
      alt: 'SQL Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'JWT',
    },
    {
      url: '../../assets/icons/restAPI.png',
      alt: 'Rest API Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'REST API',
    },
    {
      url: '../../assets/icons/csharp.png',
      alt: 'C# Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'C#',
    },
    {
      url: '../../assets/icons/java.png',
      alt: 'Java Logo',
      width: 80,
      height: 80,
      yoe: '4 yrs',
      name: 'Java',
    },
  ];
}
